2023-05-30 12:39:02,995 INFO    StreamThr :17792 [internal.py:wandb_internal():86] W&B internal server running at pid: 17792, started at: 2023-05-30 12:39:02.995974
2023-05-30 12:39:02,995 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status
2023-05-30 12:39:02,995 INFO    WriterThread:17792 [datastore.py:open_for_write():85] open: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\run-j658c2kq.wandb
2023-05-30 12:39:03,011 DEBUG   SenderThread:17792 [sender.py:send():375] send: header
2023-05-30 12:39:03,199 DEBUG   SenderThread:17792 [sender.py:send():375] send: run
2023-05-30 12:39:04,995 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: check_version
2023-05-30 12:39:04,995 INFO    SenderThread:17792 [dir_watcher.py:__init__():219] watching files in: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files
2023-05-30 12:39:04,995 INFO    SenderThread:17792 [sender.py:_start_run_threads():1124] run started: j658c2kq with start time 1685443142.995973
2023-05-30 12:39:04,995 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: summary_record
2023-05-30 12:39:04,995 INFO    SenderThread:17792 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-30 12:39:04,995 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: check_version
2023-05-30 12:39:05,995 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_created():278] file/dir created: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\wandb-summary.json
2023-05-30 12:39:06,073 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: run_start
2023-05-30 12:39:06,089 DEBUG   HandlerThread:17792 [system_info.py:__init__():31] System info init
2023-05-30 12:39:06,089 DEBUG   HandlerThread:17792 [system_info.py:__init__():46] System info init done
2023-05-30 12:39:06,089 INFO    HandlerThread:17792 [system_monitor.py:start():181] Starting system monitor
2023-05-30 12:39:06,105 INFO    SystemMonitor:17792 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-05-30 12:39:06,105 INFO    HandlerThread:17792 [system_monitor.py:probe():201] Collecting system info
2023-05-30 12:39:06,105 INFO    SystemMonitor:17792 [interfaces.py:start():190] Started cpu monitoring
2023-05-30 12:39:06,105 DEBUG   HandlerThread:17792 [system_info.py:probe():195] Probing system
2023-05-30 12:39:06,105 INFO    SystemMonitor:17792 [interfaces.py:start():190] Started disk monitoring
2023-05-30 12:39:06,105 INFO    SystemMonitor:17792 [interfaces.py:start():190] Started memory monitoring
2023-05-30 12:39:06,120 INFO    SystemMonitor:17792 [interfaces.py:start():190] Started network monitoring
2023-05-30 12:39:06,136 DEBUG   HandlerThread:17792 [system_info.py:_probe_git():180] Probing git
2023-05-30 12:39:06,480 DEBUG   HandlerThread:17792 [system_info.py:_probe_git():188] Probing git done
2023-05-30 12:39:06,480 DEBUG   HandlerThread:17792 [system_info.py:probe():240] Probing system done
2023-05-30 12:39:06,480 DEBUG   HandlerThread:17792 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19044-SP0', 'python': '3.8.16', 'heartbeatAt': '2023-05-30T10:39:06.105132', 'startedAt': '2023-05-30T10:39:02.964717', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'AdaBoostF_Heart_Failure.py', 'codePath': 'openfl-tutorials\\boosting-examples\\AdaBoostF_Heart_Failure\\workspace\\AdaBoostF_Heart_Failure.py', 'git': {'remote': 'https://github.com/alpha-unito/OpenFL-extended.git', 'commit': '3c9b6cdacb3b5cdef8384322b571b2e9b2d9dd8c'}, 'email': None, 'root': 'C:/Users/DELL/Downloads/FederatedLearning/OpenFL-extended', 'host': 'DESKTOP-5AJHE86', 'username': 'DELL', 'executable': 'C:\\Users\\DELL\\anaconda3\\envs\\myenv\\python.exe', 'cpu_count': 2, 'cpu_count_logical': 4, 'cpu_freq': {'current': 1500.0, 'min': 0.0, 'max': 2301.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 0.0, 'max': 2301.0}], 'disk': {'total': 133.58313751220703, 'used': 125.66831588745117}, 'memory': {'total': 7.874275207519531}}
2023-05-30 12:39:06,480 INFO    HandlerThread:17792 [system_monitor.py:probe():211] Finished collecting system info
2023-05-30 12:39:06,480 INFO    HandlerThread:17792 [system_monitor.py:probe():214] Publishing system info
2023-05-30 12:39:06,480 DEBUG   HandlerThread:17792 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-05-30 12:39:06,480 DEBUG   HandlerThread:17792 [system_info.py:_save_pip():67] Saving pip packages done
2023-05-30 12:39:06,480 DEBUG   HandlerThread:17792 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-05-30 12:39:06,495 ERROR   HandlerThread:17792 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] Le fichier spécifié est introuvable
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\system\system_info.py", line 81, in _save_conda
    subprocess.call(
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
2023-05-30 12:39:06,495 DEBUG   HandlerThread:17792 [system_info.py:_save_conda():86] Saving conda packages done
2023-05-30 12:39:06,495 INFO    HandlerThread:17792 [system_monitor.py:probe():216] Finished publishing system info
2023-05-30 12:39:06,526 DEBUG   SenderThread:17792 [sender.py:send():375] send: files
2023-05-30 12:39:06,526 INFO    SenderThread:17792 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-05-30 12:39:06,558 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: stop_status
2023-05-30 12:39:06,558 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: stop_status
2023-05-30 12:39:07,011 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_created():278] file/dir created: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\requirements.txt
2023-05-30 12:39:07,011 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_created():278] file/dir created: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\conda-environment.yaml
2023-05-30 12:39:07,011 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_created():278] file/dir created: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\wandb-metadata.json
2023-05-30 12:39:07,198 DEBUG   SenderThread:17792 [sender.py:send():375] send: telemetry
2023-05-30 12:39:08,026 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_created():278] file/dir created: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\output.log
2023-05-30 12:39:08,214 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:39:08,214 INFO    wandb-upload_0:17792 [upload_job.py:push():137] Uploaded file C:\Users\DELL\AppData\Local\Temp\tmpvn9nsbu0wandb\gg2jk5zx-wandb-metadata.json
2023-05-30 12:39:10,057 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_modified():295] file/dir modified: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\output.log
2023-05-30 12:39:11,073 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_modified():295] file/dir modified: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\output.log
2023-05-30 12:39:13,776 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:39:18,849 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:39:21,558 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: stop_status
2023-05-30 12:39:21,558 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: stop_status
2023-05-30 12:39:24,218 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_modified():295] file/dir modified: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\output.log
2023-05-30 12:39:24,296 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:39:29,369 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:39:34,424 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:39:35,393 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_modified():295] file/dir modified: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\config.yaml
2023-05-30 12:39:36,559 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: stop_status
2023-05-30 12:39:36,559 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: stop_status
2023-05-30 12:39:40,971 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:39:46,039 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:39:51,101 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:39:51,570 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: stop_status
2023-05-30 12:39:51,570 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: stop_status
2023-05-30 12:39:56,919 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:01,952 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:06,137 DEBUG   SystemMonitor:17792 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-05-30 12:40:06,137 DEBUG   SenderThread:17792 [sender.py:send():375] send: stats
2023-05-30 12:40:06,574 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: stop_status
2023-05-30 12:40:06,574 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: stop_status
2023-05-30 12:40:07,824 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:12,905 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:17,932 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:21,583 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: stop_status
2023-05-30 12:40:21,583 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: stop_status
2023-05-30 12:40:23,308 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:28,363 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:33,413 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:36,139 DEBUG   SenderThread:17792 [sender.py:send():375] send: stats
2023-05-30 12:40:36,607 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: stop_status
2023-05-30 12:40:36,607 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: stop_status
2023-05-30 12:40:39,265 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:44,330 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:49,393 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:40:51,611 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: stop_status
2023-05-30 12:40:51,611 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: stop_status
2023-05-30 12:40:55,177 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:41:00,220 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:41:05,293 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:41:06,147 DEBUG   SenderThread:17792 [sender.py:send():375] send: stats
2023-05-30 12:41:06,624 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: stop_status
2023-05-30 12:41:06,624 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: stop_status
2023-05-30 12:41:10,955 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:41:12,996 DEBUG   SenderThread:17792 [sender.py:send():375] send: exit
2023-05-30 12:41:12,996 INFO    SenderThread:17792 [sender.py:send_exit():598] handling exit code: 0
2023-05-30 12:41:12,996 INFO    SenderThread:17792 [sender.py:send_exit():600] handling runtime: 126
2023-05-30 12:41:12,996 INFO    SenderThread:17792 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-30 12:41:12,996 INFO    SenderThread:17792 [sender.py:send_exit():606] send defer
2023-05-30 12:41:12,996 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:13,012 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 0
2023-05-30 12:41:13,012 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:13,012 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 0
2023-05-30 12:41:13,012 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 1
2023-05-30 12:41:13,012 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:13,012 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 1
2023-05-30 12:41:13,012 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:13,012 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 1
2023-05-30 12:41:13,012 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 2
2023-05-30 12:41:13,012 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:13,012 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 2
2023-05-30 12:41:13,012 INFO    HandlerThread:17792 [system_monitor.py:finish():190] Stopping system monitor
2023-05-30 12:41:13,012 DEBUG   SystemMonitor:17792 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-05-30 12:41:13,012 DEBUG   SystemMonitor:17792 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-05-30 12:41:13,012 INFO    HandlerThread:17792 [interfaces.py:finish():202] Joined cpu monitor
2023-05-30 12:41:13,012 INFO    HandlerThread:17792 [interfaces.py:finish():202] Joined disk monitor
2023-05-30 12:41:13,012 INFO    HandlerThread:17792 [interfaces.py:finish():202] Joined memory monitor
2023-05-30 12:41:13,012 INFO    HandlerThread:17792 [interfaces.py:finish():202] Joined network monitor
2023-05-30 12:41:13,027 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:13,027 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 2
2023-05-30 12:41:13,027 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 3
2023-05-30 12:41:13,027 DEBUG   SenderThread:17792 [sender.py:send():375] send: stats
2023-05-30 12:41:13,027 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:13,027 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 3
2023-05-30 12:41:13,027 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:13,027 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 3
2023-05-30 12:41:13,027 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 4
2023-05-30 12:41:13,027 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:13,027 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 4
2023-05-30 12:41:13,027 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:13,027 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 4
2023-05-30 12:41:13,027 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 5
2023-05-30 12:41:13,027 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:13,027 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 5
2023-05-30 12:41:13,027 DEBUG   SenderThread:17792 [sender.py:send():375] send: summary
2023-05-30 12:41:13,043 INFO    SenderThread:17792 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-30 12:41:13,043 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:13,043 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 5
2023-05-30 12:41:13,043 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 6
2023-05-30 12:41:13,043 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:13,043 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 6
2023-05-30 12:41:13,043 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:13,043 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 6
2023-05-30 12:41:13,043 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 7
2023-05-30 12:41:13,043 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:41:13,043 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:13,043 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 7
2023-05-30 12:41:13,043 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:13,043 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 7
2023-05-30 12:41:13,870 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_modified():295] file/dir modified: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\wandb-summary.json
2023-05-30 12:41:14,067 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: poll_exit
2023-05-30 12:41:14,876 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_modified():295] file/dir modified: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\output.log
2023-05-30 12:41:15,450 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 8
2023-05-30 12:41:15,458 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: poll_exit
2023-05-30 12:41:15,458 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:15,458 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 8
2023-05-30 12:41:15,458 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:15,458 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 8
2023-05-30 12:41:15,522 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 9
2023-05-30 12:41:15,530 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:15,530 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 9
2023-05-30 12:41:15,530 DEBUG   SenderThread:17792 [sender.py:send():375] send: artifact
2023-05-30 12:41:15,892 INFO    Thread-16 :17792 [dir_watcher.py:_on_file_modified():295] file/dir modified: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\output.log
2023-05-30 12:41:17,409 INFO    SenderThread:17792 [sender.py:send_artifact():1474] sent artifact job-https___github.com_alpha-unito_OpenFL-extended.git_openfl-t..es_AdaBoostF_Heart_Failure_workspace_AdaBoostF_Heart_Failure.py - {'id': 'QXJ0aWZhY3Q6NDQyMzg1Mzc4', 'digest': '9177cc921fff83e2f5ea32716677d4d0', 'state': 'COMMITTED', 'aliases': [{'artifactCollectionName': 'job-https___github.com_alpha-unito_OpenFL-extended.git_openfl-t..es_AdaBoostF_Heart_Failure_workspace_AdaBoostF_Heart_Failure.py', 'alias': 'latest'}, {'artifactCollectionName': 'job-https___github.com_alpha-unito_OpenFL-extended.git_openfl-t..es_AdaBoostF_Heart_Failure_workspace_AdaBoostF_Heart_Failure.py', 'alias': 'v0'}], 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjY2NjczMjc3', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6NDQ2NTE3NzY4', 'versionIndex': 1}}, 'version': 'v0'}
2023-05-30 12:41:17,409 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:17,409 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 9
2023-05-30 12:41:17,409 INFO    SenderThread:17792 [dir_watcher.py:finish():365] shutting down directory watcher
2023-05-30 12:41:17,919 INFO    SenderThread:17792 [dir_watcher.py:finish():395] scan: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files
2023-05-30 12:41:17,919 INFO    SenderThread:17792 [dir_watcher.py:finish():409] scan save: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\conda-environment.yaml conda-environment.yaml
2023-05-30 12:41:17,919 INFO    SenderThread:17792 [dir_watcher.py:finish():409] scan save: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\config.yaml config.yaml
2023-05-30 12:41:17,919 INFO    SenderThread:17792 [dir_watcher.py:finish():409] scan save: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\output.log output.log
2023-05-30 12:41:17,935 INFO    SenderThread:17792 [dir_watcher.py:finish():409] scan save: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\requirements.txt requirements.txt
2023-05-30 12:41:17,943 INFO    SenderThread:17792 [dir_watcher.py:finish():409] scan save: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\wandb-metadata.json wandb-metadata.json
2023-05-30 12:41:17,943 INFO    SenderThread:17792 [dir_watcher.py:finish():409] scan save: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\wandb-summary.json wandb-summary.json
2023-05-30 12:41:17,967 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 10
2023-05-30 12:41:17,967 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:17,967 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 10
2023-05-30 12:41:17,975 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:17,975 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 10
2023-05-30 12:41:17,983 INFO    SenderThread:17792 [file_pusher.py:finish():168] shutting down file pusher
2023-05-30 12:41:19,160 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: keepalive
2023-05-30 12:41:19,377 ERROR   wandb-upload_0:17792 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/config.yaml?Expires=1685529675&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=nQUMJ2ZqKQ3%2FAmjvYZECm6o0oyK0eWXKwHf4072X3JfjKNaSg6xvVA4UvlymwnTiH%2BR4reK8U7P%2BgJlFCpAFCZfIkIvhWtkcq%2BHpcrDXd%2BcDs5B8Qso%2BKDtxkzBOt6SsHOZkmlSjLX97liG4knJqE97ZfZQTIDQ6eBgW8KN3OCmDFpUj4X8MkK%2F973ZQkaaYf6qnLicEEyI%2BuSU7VMKy%2Bqx4DRqBl3U51yc7VTkrPkYQ5NEswL96n%2B9OHBfkIXxp0pV%2BinG7Pv9xliXrTNrynRbXl35W833pWXfCfuDMZ4BSRST%2FqCGDQvwNxzCgIbigG012RhsSVS8%2FjpAoz8R39A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/config.yaml?Expires=1685529675&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=nQUMJ2ZqKQ3%2FAmjvYZECm6o0oyK0eWXKwHf4072X3JfjKNaSg6xvVA4UvlymwnTiH%2BR4reK8U7P%2BgJlFCpAFCZfIkIvhWtkcq%2BHpcrDXd%2BcDs5B8Qso%2BKDtxkzBOt6SsHOZkmlSjLX97liG4knJqE97ZfZQTIDQ6eBgW8KN3OCmDFpUj4X8MkK%2F973ZQkaaYf6qnLicEEyI%2BuSU7VMKy%2Bqx4DRqBl3U51yc7VTkrPkYQ5NEswL96n%2B9OHBfkIXxp0pV%2BinG7Pv9xliXrTNrynRbXl35W833pWXfCfuDMZ4BSRST%2FqCGDQvwNxzCgIbigG012RhsSVS8%2FjpAoz8R39A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B477CC2E50>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-05-30 12:41:19,377 INFO    wandb-upload_1:17792 [upload_job.py:push():137] Uploaded file C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\output.log
2023-05-30 12:41:19,377 ERROR   wandb-upload_0:17792 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '449'}
2023-05-30 12:41:19,377 ERROR   wandb-upload_0:17792 [internal_api.py:upload_file():2103] upload_file response body: 
2023-05-30 12:41:20,085 ERROR   wandb-upload_3:17792 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/wandb-summary.json?Expires=1685529677&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fOyvyNYNRepcnIWvNifxpL4HJqfQsDc8gcLesTPxTmzlou9dGIxUI1jJXu0N4FOocATNSh3LkiuZrd3fJizWHTrx0s9i9L3Ws0uNekuQihpPDsPkLHZafnjdI8Q3rPAbN%2F%2Flf8V%2BmSdPgmwgjJC2DhQNHVhB9hU%2BSaZXTnkPlUFVJfDXFtdBhYujB5%2FXp2y7vR4dWzGixOUzR5gPcYHrymQB%2BAx2XouBafTX6TyYXvcCst4SkS5bmJ8kTZFCTO4XBtxBY4HdU1V%2BN8ROMbwUuqppKUBk2cH19FVwO879J%2F30jBOr3zIwwsZPjDnQTngzeslcWtfrdKmJxysvJN7irw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/wandb-summary.json?Expires=1685529677&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fOyvyNYNRepcnIWvNifxpL4HJqfQsDc8gcLesTPxTmzlou9dGIxUI1jJXu0N4FOocATNSh3LkiuZrd3fJizWHTrx0s9i9L3Ws0uNekuQihpPDsPkLHZafnjdI8Q3rPAbN%2F%2Flf8V%2BmSdPgmwgjJC2DhQNHVhB9hU%2BSaZXTnkPlUFVJfDXFtdBhYujB5%2FXp2y7vR4dWzGixOUzR5gPcYHrymQB%2BAx2XouBafTX6TyYXvcCst4SkS5bmJ8kTZFCTO4XBtxBY4HdU1V%2BN8ROMbwUuqppKUBk2cH19FVwO879J%2F30jBOr3zIwwsZPjDnQTngzeslcWtfrdKmJxysvJN7irw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B477CB1D60>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-05-30 12:41:20,085 ERROR   wandb-upload_3:17792 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28'}
2023-05-30 12:41:20,085 ERROR   wandb-upload_3:17792 [internal_api.py:upload_file():2103] upload_file response body: 
2023-05-30 12:41:20,093 ERROR   wandb-upload_2:17792 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/requirements.txt?Expires=1685529677&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=jEaJqNI7aLus351RDMWvO9ZFJFAECMmfwjihNdD8EHxFHB1Gpi6OLDKy0UlIf8Bl%2BS0kRYZRBsmUPwclp79BdjdquPWrdW0kfLf%2BUN1gA5vweZYPDn5TJA2mqt5VG8nS3keN40Zq1wHTvH5sSV3tDn%2Bkw0ZrnDWxtS4kOUpe%2F7AvHxcpq5juSX90Lor9kxyFB0f6PVQiRjIrBl00EYSxEfJKpHtbGnJOvMVSMbj28Jglv0kNTj3%2Fbk%2BGaw2qEEEurV2%2FX5%2BmZVnMZca245gr%2BVa2z50b4mNKH5GUYtJkox0xrCTV2y%2FZCUeVIHH35VLPwg7TYmaqPupdVj7mDTlKyg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/requirements.txt?Expires=1685529677&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=jEaJqNI7aLus351RDMWvO9ZFJFAECMmfwjihNdD8EHxFHB1Gpi6OLDKy0UlIf8Bl%2BS0kRYZRBsmUPwclp79BdjdquPWrdW0kfLf%2BUN1gA5vweZYPDn5TJA2mqt5VG8nS3keN40Zq1wHTvH5sSV3tDn%2Bkw0ZrnDWxtS4kOUpe%2F7AvHxcpq5juSX90Lor9kxyFB0f6PVQiRjIrBl00EYSxEfJKpHtbGnJOvMVSMbj28Jglv0kNTj3%2Fbk%2BGaw2qEEEurV2%2FX5%2BmZVnMZca245gr%2BVa2z50b4mNKH5GUYtJkox0xrCTV2y%2FZCUeVIHH35VLPwg7TYmaqPupdVj7mDTlKyg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B477CB1130>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-05-30 12:41:20,093 ERROR   wandb-upload_2:17792 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3406'}
2023-05-30 12:41:20,093 ERROR   wandb-upload_2:17792 [internal_api.py:upload_file():2103] upload_file response body: 
2023-05-30 12:41:20,610 ERROR   wandb-upload_0:17792 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/config.yaml?Expires=1685529675&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=nQUMJ2ZqKQ3%2FAmjvYZECm6o0oyK0eWXKwHf4072X3JfjKNaSg6xvVA4UvlymwnTiH%2BR4reK8U7P%2BgJlFCpAFCZfIkIvhWtkcq%2BHpcrDXd%2BcDs5B8Qso%2BKDtxkzBOt6SsHOZkmlSjLX97liG4knJqE97ZfZQTIDQ6eBgW8KN3OCmDFpUj4X8MkK%2F973ZQkaaYf6qnLicEEyI%2BuSU7VMKy%2Bqx4DRqBl3U51yc7VTkrPkYQ5NEswL96n%2B9OHBfkIXxp0pV%2BinG7Pv9xliXrTNrynRbXl35W833pWXfCfuDMZ4BSRST%2FqCGDQvwNxzCgIbigG012RhsSVS8%2FjpAoz8R39A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/config.yaml?Expires=1685529675&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=nQUMJ2ZqKQ3%2FAmjvYZECm6o0oyK0eWXKwHf4072X3JfjKNaSg6xvVA4UvlymwnTiH%2BR4reK8U7P%2BgJlFCpAFCZfIkIvhWtkcq%2BHpcrDXd%2BcDs5B8Qso%2BKDtxkzBOt6SsHOZkmlSjLX97liG4knJqE97ZfZQTIDQ6eBgW8KN3OCmDFpUj4X8MkK%2F973ZQkaaYf6qnLicEEyI%2BuSU7VMKy%2Bqx4DRqBl3U51yc7VTkrPkYQ5NEswL96n%2B9OHBfkIXxp0pV%2BinG7Pv9xliXrTNrynRbXl35W833pWXfCfuDMZ4BSRST%2FqCGDQvwNxzCgIbigG012RhsSVS8%2FjpAoz8R39A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B477CB1EB0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-05-30 12:41:20,610 ERROR   wandb-upload_0:17792 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '449'}
2023-05-30 12:41:20,610 ERROR   wandb-upload_0:17792 [internal_api.py:upload_file():2103] upload_file response body: 
2023-05-30 12:41:21,102 ERROR   wandb-upload_3:17792 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/wandb-summary.json?Expires=1685529677&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fOyvyNYNRepcnIWvNifxpL4HJqfQsDc8gcLesTPxTmzlou9dGIxUI1jJXu0N4FOocATNSh3LkiuZrd3fJizWHTrx0s9i9L3Ws0uNekuQihpPDsPkLHZafnjdI8Q3rPAbN%2F%2Flf8V%2BmSdPgmwgjJC2DhQNHVhB9hU%2BSaZXTnkPlUFVJfDXFtdBhYujB5%2FXp2y7vR4dWzGixOUzR5gPcYHrymQB%2BAx2XouBafTX6TyYXvcCst4SkS5bmJ8kTZFCTO4XBtxBY4HdU1V%2BN8ROMbwUuqppKUBk2cH19FVwO879J%2F30jBOr3zIwwsZPjDnQTngzeslcWtfrdKmJxysvJN7irw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/wandb-summary.json?Expires=1685529677&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fOyvyNYNRepcnIWvNifxpL4HJqfQsDc8gcLesTPxTmzlou9dGIxUI1jJXu0N4FOocATNSh3LkiuZrd3fJizWHTrx0s9i9L3Ws0uNekuQihpPDsPkLHZafnjdI8Q3rPAbN%2F%2Flf8V%2BmSdPgmwgjJC2DhQNHVhB9hU%2BSaZXTnkPlUFVJfDXFtdBhYujB5%2FXp2y7vR4dWzGixOUzR5gPcYHrymQB%2BAx2XouBafTX6TyYXvcCst4SkS5bmJ8kTZFCTO4XBtxBY4HdU1V%2BN8ROMbwUuqppKUBk2cH19FVwO879J%2F30jBOr3zIwwsZPjDnQTngzeslcWtfrdKmJxysvJN7irw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B477CC2EB0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-05-30 12:41:21,102 ERROR   wandb-upload_3:17792 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28'}
2023-05-30 12:41:21,102 ERROR   wandb-upload_3:17792 [internal_api.py:upload_file():2103] upload_file response body: 
2023-05-30 12:41:21,102 INFO    wandb-upload_3:17792 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002B477CC2EB0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/wandb-summary.json?Expires=1685529677&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fOyvyNYNRepcnIWvNifxpL4HJqfQsDc8gcLesTPxTmzlou9dGIxUI1jJXu0N4FOocATNSh3LkiuZrd3fJizWHTrx0s9i9L3Ws0uNekuQihpPDsPkLHZafnjdI8Q3rPAbN%2F%2Flf8V%2BmSdPgmwgjJC2DhQNHVhB9hU%2BSaZXTnkPlUFVJfDXFtdBhYujB5%2FXp2y7vR4dWzGixOUzR5gPcYHrymQB%2BAx2XouBafTX6TyYXvcCst4SkS5bmJ8kTZFCTO4XBtxBY4HdU1V%2BN8ROMbwUuqppKUBk2cH19FVwO879J%2F30jBOr3zIwwsZPjDnQTngzeslcWtfrdKmJxysvJN7irw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B477CC2EB0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/wandb-summary.json?Expires=1685529677&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fOyvyNYNRepcnIWvNifxpL4HJqfQsDc8gcLesTPxTmzlou9dGIxUI1jJXu0N4FOocATNSh3LkiuZrd3fJizWHTrx0s9i9L3Ws0uNekuQihpPDsPkLHZafnjdI8Q3rPAbN%2F%2Flf8V%2BmSdPgmwgjJC2DhQNHVhB9hU%2BSaZXTnkPlUFVJfDXFtdBhYujB5%2FXp2y7vR4dWzGixOUzR5gPcYHrymQB%2BAx2XouBafTX6TyYXvcCst4SkS5bmJ8kTZFCTO4XBtxBY4HdU1V%2BN8ROMbwUuqppKUBk2cH19FVwO879J%2F30jBOr3zIwwsZPjDnQTngzeslcWtfrdKmJxysvJN7irw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B477CC2EB0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 2123, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 2094, in upload_file
    response = self._upload_file_session.put(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-05-30 12:41:21,196 ERROR   wandb-upload_2:17792 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/requirements.txt?Expires=1685529677&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=jEaJqNI7aLus351RDMWvO9ZFJFAECMmfwjihNdD8EHxFHB1Gpi6OLDKy0UlIf8Bl%2BS0kRYZRBsmUPwclp79BdjdquPWrdW0kfLf%2BUN1gA5vweZYPDn5TJA2mqt5VG8nS3keN40Zq1wHTvH5sSV3tDn%2Bkw0ZrnDWxtS4kOUpe%2F7AvHxcpq5juSX90Lor9kxyFB0f6PVQiRjIrBl00EYSxEfJKpHtbGnJOvMVSMbj28Jglv0kNTj3%2Fbk%2BGaw2qEEEurV2%2FX5%2BmZVnMZca245gr%2BVa2z50b4mNKH5GUYtJkox0xrCTV2y%2FZCUeVIHH35VLPwg7TYmaqPupdVj7mDTlKyg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/requirements.txt?Expires=1685529677&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=jEaJqNI7aLus351RDMWvO9ZFJFAECMmfwjihNdD8EHxFHB1Gpi6OLDKy0UlIf8Bl%2BS0kRYZRBsmUPwclp79BdjdquPWrdW0kfLf%2BUN1gA5vweZYPDn5TJA2mqt5VG8nS3keN40Zq1wHTvH5sSV3tDn%2Bkw0ZrnDWxtS4kOUpe%2F7AvHxcpq5juSX90Lor9kxyFB0f6PVQiRjIrBl00EYSxEfJKpHtbGnJOvMVSMbj28Jglv0kNTj3%2Fbk%2BGaw2qEEEurV2%2FX5%2BmZVnMZca245gr%2BVa2z50b4mNKH5GUYtJkox0xrCTV2y%2FZCUeVIHH35VLPwg7TYmaqPupdVj7mDTlKyg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B477CC1F10>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-05-30 12:41:21,196 ERROR   wandb-upload_2:17792 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3406'}
2023-05-30 12:41:21,196 ERROR   wandb-upload_2:17792 [internal_api.py:upload_file():2103] upload_file response body: 
2023-05-30 12:41:23,109 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:41:23,117 ERROR   wandb-upload_0:17792 [internal_api.py:upload_file():2099] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/config.yaml?Expires=1685529675&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=nQUMJ2ZqKQ3%2FAmjvYZECm6o0oyK0eWXKwHf4072X3JfjKNaSg6xvVA4UvlymwnTiH%2BR4reK8U7P%2BgJlFCpAFCZfIkIvhWtkcq%2BHpcrDXd%2BcDs5B8Qso%2BKDtxkzBOt6SsHOZkmlSjLX97liG4knJqE97ZfZQTIDQ6eBgW8KN3OCmDFpUj4X8MkK%2F973ZQkaaYf6qnLicEEyI%2BuSU7VMKy%2Bqx4DRqBl3U51yc7VTkrPkYQ5NEswL96n%2B9OHBfkIXxp0pV%2BinG7Pv9xliXrTNrynRbXl35W833pWXfCfuDMZ4BSRST%2FqCGDQvwNxzCgIbigG012RhsSVS8%2FjpAoz8R39A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/harrak-oussama2002/Federated_Learning_Heart_Failure/j658c2kq/config.yaml?Expires=1685529675&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=nQUMJ2ZqKQ3%2FAmjvYZECm6o0oyK0eWXKwHf4072X3JfjKNaSg6xvVA4UvlymwnTiH%2BR4reK8U7P%2BgJlFCpAFCZfIkIvhWtkcq%2BHpcrDXd%2BcDs5B8Qso%2BKDtxkzBOt6SsHOZkmlSjLX97liG4knJqE97ZfZQTIDQ6eBgW8KN3OCmDFpUj4X8MkK%2F973ZQkaaYf6qnLicEEyI%2BuSU7VMKy%2Bqx4DRqBl3U51yc7VTkrPkYQ5NEswL96n%2B9OHBfkIXxp0pV%2BinG7Pv9xliXrTNrynRbXl35W833pWXfCfuDMZ4BSRST%2FqCGDQvwNxzCgIbigG012RhsSVS8%2FjpAoz8R39A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B477CC16D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-05-30 12:41:23,117 ERROR   wandb-upload_0:17792 [internal_api.py:upload_file():2101] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '449'}
2023-05-30 12:41:23,117 ERROR   wandb-upload_0:17792 [internal_api.py:upload_file():2103] upload_file response body: 
2023-05-30 12:41:23,884 INFO    wandb-upload_2:17792 [upload_job.py:push():137] Uploaded file C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\requirements.txt
2023-05-30 12:41:23,962 INFO    wandb-upload_3:17792 [upload_job.py:push():137] Uploaded file C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\wandb-summary.json
2023-05-30 12:41:24,209 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: keepalive
2023-05-30 12:41:27,779 INFO    wandb-upload_0:17792 [upload_job.py:push():137] Uploaded file C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\files\config.yaml
2023-05-30 12:41:27,982 INFO    Thread-15 :17792 [sender.py:transition_state():626] send defer: 11
2023-05-30 12:41:27,982 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:27,982 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 11
2023-05-30 12:41:27,982 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:27,982 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 11
2023-05-30 12:41:27,982 INFO    SenderThread:17792 [file_pusher.py:join():173] waiting for file pusher
2023-05-30 12:41:27,982 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 12
2023-05-30 12:41:27,982 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:27,982 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 12
2023-05-30 12:41:27,982 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:27,982 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 12
2023-05-30 12:41:28,373 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 13
2023-05-30 12:41:28,373 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:28,373 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 13
2023-05-30 12:41:28,373 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: status_report
2023-05-30 12:41:28,373 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:28,373 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 13
2023-05-30 12:41:28,373 INFO    SenderThread:17792 [sender.py:transition_state():626] send defer: 14
2023-05-30 12:41:28,389 DEBUG   SenderThread:17792 [sender.py:send():375] send: final
2023-05-30 12:41:28,389 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: defer
2023-05-30 12:41:28,389 DEBUG   SenderThread:17792 [sender.py:send():375] send: footer
2023-05-30 12:41:28,389 INFO    HandlerThread:17792 [handler.py:handle_request_defer():170] handle defer: 14
2023-05-30 12:41:28,389 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: defer
2023-05-30 12:41:28,389 INFO    SenderThread:17792 [sender.py:send_request_defer():622] handle sender defer: 14
2023-05-30 12:41:28,389 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: poll_exit
2023-05-30 12:41:28,389 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: server_info
2023-05-30 12:41:28,389 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: get_summary
2023-05-30 12:41:28,389 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: sampled_history
2023-05-30 12:41:28,389 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: poll_exit
2023-05-30 12:41:28,389 DEBUG   SenderThread:17792 [sender.py:send_request():402] send_request: server_info
2023-05-30 12:41:28,654 INFO    MainThread:17792 [wandb_run.py:_footer_history_summary_info():3476] rendering history
2023-05-30 12:41:28,654 INFO    MainThread:17792 [wandb_run.py:_footer_history_summary_info():3508] rendering summary
2023-05-30 12:41:28,654 INFO    MainThread:17792 [wandb_run.py:_footer_sync_info():3434] logging synced files
2023-05-30 12:41:28,654 DEBUG   HandlerThread:17792 [handler.py:handle_request():144] handle_request: shutdown
2023-05-30 12:41:28,654 INFO    HandlerThread:17792 [handler.py:finish():845] shutting down handler
2023-05-30 12:41:29,401 INFO    WriterThread:17792 [datastore.py:close():298] close: C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\AdaBoostF_Heart_Failure\workspace\wandb\run-20230530_123902-j658c2kq\run-j658c2kq.wandb
2023-05-30 12:41:29,667 INFO    SenderThread:17792 [sender.py:finish():1550] shutting down sender
2023-05-30 12:41:29,667 INFO    SenderThread:17792 [file_pusher.py:finish():168] shutting down file pusher
2023-05-30 12:41:29,667 INFO    SenderThread:17792 [file_pusher.py:join():173] waiting for file pusher
